### ISSUE TITLE
Ready to submit. Final steps:

### ISSUE THREAD

**Issue by labarba** [barbagroup/rescience-rollingpitching#1]
- [x] Upload the repro-packs (18G) to Zenodo and get a DOI.
- [x] Reference the DOI in the README of the code repo and in the manuscript.
- [x] Cut a GitHub release of the code repo.
- [x] Upload the release to Zenodo and get a DOI.
- [x] Reference the DOI in the README of the code repo and in the manuscript.
- [x] Create a GitHub tag for the manuscript repo.
- [x] Upload manuscript to arXiv using the `arxiv` branch of `rescience-rollingpitching`.
- [x] Submit manuscript to ReScience using the Issues tracker of `ReScience/submissions`.

**Comment by labarba** [comment]
I will do the arXiv submission, once all the Zenodo DOIs are added. Ping when ready.

**Comment by labarba** [comment]
From @mesnardo 👍 

- Uploaded and published the repro-packs on Zenodo: [10.5281/zenodo.4732946](https://doi.org/10.5281/zenodo.4732946)
- Released petibm-rollingpitching on GitHub: [v2021.05.02](https://github.com/barbagroup/petibm-rollingpitching/releases/tag/v2021.05.02)
- Uploaded and published code repo on Zenodo: [10.5281/zenodo.4733323](https://doi.org/10.5281/zenodo.4733323)
- Created tag 2021.05.02 on the manuscript repo
- Created an [orphan branch](https://github.com/barbagroup/rescience-rollingpitching/tree/submission-2021.05.02) with just the PDF of the article (to reference the url on the submission issue)
- Opened an issue on ReScience C to request a review of the manuscript: [ReScience/submissions#55](https://github.com/ReScience/submissions/issues/55)

**Comment by mesnardo** [comment]
Closing (manuscript submitted to ReScience C).
